Crear array de 10 números aleatorios entre 1 y 100

In [7]:

import numpy as np

arr = np.random.randint(1, 101, 10)

max_value = np.max(arr)
min_value = np.min(arr)
mean_value = np.mean(arr)

print("Array:", arr)
print("Máximo:", max_value)
print("Mínimo:", min_value)
print("Media:", mean_value)

Array: [ 33  64  64  16  71  54  66 100  74  30]
Máximo: 100
Mínimo: 16
Media: 57.2


Crear dos arrays de 5 elementos

In [ ]:

a = np.random.randint(1, 51, 5)
b = np.random.randint(1, 51, 5)

suma = a + b
resta = a - b
producto = a * b
division = a / b

print("Array A:", a)
print("Array B:", b)
print("Suma:", suma)
print("Resta:", resta)
print("Producto:", producto)
print("División:", division)


Array A: [28 34  5  9 19]
Array B: [14  9 49 27  4]
Suma: [42 43 54 36 23]
Resta: [ 14  25 -44 -18  15]
Producto: [392 306 245 243  76]
División: [2.         3.77777778 0.10204082 0.33333333 4.75      ]


Crear matriz identidad 5x5

In [ ]:

import numpy as np

matriz = np.eye(5)

np.fill_diagonal(np.fliplr(matriz), 7)

print("Matriz modificada:\n", matriz)


Matriz modificada:
 [[1. 0. 0. 0. 7.]
 [0. 1. 0. 7. 0.]
 [0. 0. 7. 0. 0.]
 [0. 7. 0. 1. 0.]
 [7. 0. 0. 0. 1.]]


Crear array de 20 valores aleatorios entre 1 y 100

In [ ]:

numeros = np.random.randint(1, 101, 20)

mayores_50 = numeros[numeros > 50]

print("Array original:", numeros)
print("Valores mayores a 50:", mayores_50)


Array original: [31 43 16 18 83 72 47 10 17 61 67 51 25 85 45 58 63 50 10  1]
Valores mayores a 50: [83 72 61 67 51 85 58 63]


Función que genere los primeros n números de la secuencia de Fibonacci

In [ ]:

def fibonacci(n):
    fib = np.zeros(n, dtype=int)
    fib[0], fib[1] = 0, 1  # Primeros dos valores
    
    for i in range(2, n):
        fib[i] = fib[i - 1] + fib[i - 2]
    
    return fib

print("Fibonacci (10 términos):", fibonacci(10))


Fibonacci (10 términos): [ 0  1  1  2  3  5  8 13 21 34]
